In [1]:
import pandas as pd
import numpy as np
import pathlib
import random
import re
import os

#os.chdir(r"D:\\박준호\\2024년\\NLP-Standard-Dialect-Transformation")

# 모두 방언 부분집합만으로 구성

In [3]:
df = pd.read_csv("../datas/jeonla/jeonla_dialect_bpe_integration.csv", index_col=0)
df

,방언,표준어,연령대,출처 파일,길이,셋
0,ë§īìĥģ ĠìĻĦìłĦ ĠëıĪìĿ´ Ġê¸īíķĺê²Į ĠíķĦìļĶíķľ Ġ...,ë§īìĥģ ĠìĻĦìłĦ ĠëıĪìĿ´ Ġê¸īíķĺê²Į ĠíķĦìļĶíķľ Ġ...,20대,DJSX20002683.json,15,train
1,ì¢ĭìĿĢ Ġì¶ĶìĸµìĿ´ ĠìŀĪìĸ´ê°Ģì§Ģê³ł Ġëĭ¤ìĭľ ĠíĤ...,ì¢ĭìĿĢ Ġì¶ĶìĸµìĿ´ ĠìŀĪìĸ´ê°Ģì§Ģê³ł Ġëĭ¤ìĭľ ĠíĤ...,30대,DJDG20002125.json,8,train
2,ì«Į Ġë³´ë©´ ĠìĿ¸ìłľ ĠìĦ¸ê³Ħ ĠìĿ¸ìłľ,ì¡°ê¸Ī Ġë³´ë©´ ĠìĿ¸ìłľ ĠìĦ¸ê³Ħ ĠìĿ¸ìłľ,30대,DJSX20004304.json,5,train
3,ê°Ģìĭľ ëĤĺëĵ¤ ĠìŀĪìľ¼ëĭĪê¹Į ĠëŃĲ ~ ĠìĿ¼ë¶ĢëŁ¬ ...,ê³Ħ ì§ĳ ìķĦìĿ´ëĵ¤ ĠìŀĪìľ¼ëĭĪê¹Į ĠëŃĲ ~ ĠìĿ¼ë¶Ģ...,20대,DJDG20001833.json,12,train
4,ê±°ê¸°ìĦľ Ġìĸ´ ĠìłĢ ĠìĥĪëģ¼ ĠìĻľ Ġë¯¸ëĭĪ ìĸ¸ Ġ...,ê±°ê¸°ìĦľ Ġìĸ´ ĠìłĢ ĠìĥĪëģ¼ ĠìĻľ Ġë¯¸ëĭĪ ìĸ¸ Ġ...,20대,DJDD20000034.json,12,train
...,...,...,...,...,...,...
275119,ìĿ¼ë°ĺ ĠìĤ¬ëŀĮëĵ¤ëıĦ Ġìī½ê²Į Ġìī½ê²Į Ġêµ¬ë§¤íķ...,ìĿ¼ë°ĺ ĠìĤ¬ëŀĮëĵ¤ëıĦ Ġìī½ê²Į Ġìī½ê²Į Ġêµ¬ë§¤íķ...,30대,DJSX20003150.json,12,test
275120,ëįĶ ĠëĤĺìķĦ ê°ĢìĦľ ĠëĤĺì¤ĳìĹĲëĬĶ ĠíķĺëĬĺ ĠëıĦì...,ëįĶ ĠëĤĺìķĦ ê°ĢìĦľ ĠëĤĺì¤ĳìĹĲëĬĶ ĠíķĺëĬĺ ĠëıĦì...,30대,DJSX20003150.json,8,test
275123,ìĸ´ ĠíĥĿ ìĭľê°Ģ ĠìŀĪìĿĦ Ġê±° Ġê°Ļìķł .,ìĸ´ ĠíĥĿ ìĭľê°Ģ ĠìŀĪìĿĦ Ġê±° Ġê°Ļìķł .,30대,DJSX20003150.json,5,test
275133,ìĿ´ Ġì²ľ ĠìĿ´ ĠìĭŃ Ġì¹ł ĠëħĦìĿ´ ĠìĿ´ Ġì²ľ ĠìĿ´...,ìĿ´ Ġì²ľ ĠìĿ´ ĠìĭŃ Ġì¹ł ĠëħĦìĿ´ ĠìĿ´ Ġì²ľ ĠìĿ´...,30대,DJSX20003150.json,12,test
275134,ê·¼ëį° Ġë°ľíĳľë¥¼ Ġíķľëĭ¤ê³ł Ġíķ´ìĦľ ĠìĿ´ê²Į ĠëĶ±,ê·¼ëį° Ġë°ľíĳľë¥¼ Ġíķľëĭ¤ê³ł Ġíķ´ìĦľ ĠìĿ´ê²Į ĠëĶ±,30대,DJSX20003150.json,6,test

In [8]:
dialect_df = df[df['방언'] != df["표준어"]]

dialect_df

,방언,표준어,연령대,출처 파일,길이,셋
0,ë§īìĥģ ĠìĻĦìłĦ ĠëıĪìĿ´ Ġê¸īíķĺê²Į ĠíķĦìļĶíķľ Ġ...,ë§īìĥģ ĠìĻĦìłĦ ĠëıĪìĿ´ Ġê¸īíķĺê²Į ĠíķĦìļĶíķľ Ġ...,20대,DJSX20002683.json,15,train
2,ì«Į Ġë³´ë©´ ĠìĿ¸ìłľ ĠìĦ¸ê³Ħ ĠìĿ¸ìłľ,ì¡°ê¸Ī Ġë³´ë©´ ĠìĿ¸ìłľ ĠìĦ¸ê³Ħ ĠìĿ¸ìłľ,30대,DJSX20004304.json,5,train
3,ê°Ģìĭľ ëĤĺëĵ¤ ĠìŀĪìľ¼ëĭĪê¹Į ĠëŃĲ ~ ĠìĿ¼ë¶ĢëŁ¬ ...,ê³Ħ ì§ĳ ìķĦìĿ´ëĵ¤ ĠìŀĪìľ¼ëĭĪê¹Į ĠëŃĲ ~ ĠìĿ¼ë¶Ģ...,20대,DJDG20001833.json,12,train
5,ëĦĪë¬´ Ġë§ī ĠìĿ¼ì¼Ģ Ġì¢Ģ Ġë§ĲìĿ´ Ġë§İì§Ģ ĠìķĬê³ł,ëĦĪë¬´ Ġë§ī ĠìĿ´ëłĩê²Į Ġì¢Ģ Ġë§ĲìĿ´ Ġë§İì§Ģ Ġì...,20대,DJDD20000062.json,7,train
7,ê·¼ëĶĶ ĠìĹ¬ê¸°ìĦľ Ġì©¨ìĿ¼ ĠëŃĲ ~ Ġìľłëªħíķľ Ġê...,ê·¸ëŁ°ëį° ĠìĹ¬ê¸°ìĦľ ĠìłľìĿ¼ ĠëŃĲ ~ Ġìľłëªħíķľ...,30대,DJDG20002472.json,7,train
...,...,...,...,...,...,...
274803,ê·¸ëĥ¥ Ġìļ´ëıĻ Ġì«Į Ġíķł ĠëķĮ Ġë§ī Ġê·¸ëŁ° Ġê±...,ê·¸ëĥ¥ Ġìļ´ëıĻ Ġì¡°ê¸Ī Ġíķł ĠëķĮ Ġë§ī Ġê·¸ëŁ° ...,30대,DJSX20003149.json,12,test
274818,ë§ŀìĸ´ Ġì¢Įìļ°ëªħ ìĿ´ëĤĺ Ġê°Ģì¹ĺê´Ģ ĠìĿ´ëĤĺ Ġë...,ë§ŀìĸ´ Ġì¢Įìļ°ëªħ ìĿ´ëĤĺ Ġê°Ģì¹ĺê´Ģ ĠìĿ´ëĤĺ Ġë...,30대,DJSX20003149.json,7,test
274854,ìķĦ ĠìĿ´ê±´ Ġì§Ħì§ľ Ġë§ŀëĬĶ Ġë§ĲìĿ´ìĹ¬ .,ìķĦ ĠìĿ´ê±´ Ġì§Ħì§ľ Ġë§ŀëĬĶ Ġë§ĲìĿ´ìķ¼ .,30대,DJSX20003149.json,5,test
274914,ìŀĲ ìľ¨ ì£¼íĸī ĠìŀĲëıĻì°¨ Ġê·¼ëį° Ġì«Į Ġë¬´ìĦŃ...,ìŀĲ ìľ¨ ì£¼íĸī ĠìŀĲëıĻì°¨ Ġê·¼ëį° Ġì¡°ê¸Ī Ġë¬´...,30대,DJSX20003150.json,7,test
274958,ëĺĲ ĠìłĢê¸° ìĹĲìĦľ ĠëıĪ Ġë²Ī ĠìĤ¬ëŀĮ ĠëŃĲ Ġê²ģ...,ëĺĲ ĠìłĢê¸° ìĹĲìĦľ ĠëıĪ Ġë²Ī ĠìĤ¬ëŀĮ ĠëŃĲ ĠìķĦ...,30대,DJSX20003150.json,10,test

In [11]:
print(len(dialect_df[dialect_df["셋"] == "train"]), len(df[df["셋"] == "train"]))

254207 508414

In [12]:
def remove_standard(path_to_data, region, token):
    file_path = os.path.join(path_to_data, "{0}_dialect_{1}_integration.csv".format(region, token))
    
    df = pd.read_csv(file_path, index_col=0)
    
    dialect_df = df[df['방언'] != df["표준어"]]
    out_file_path = os.path.join(path_to_data, "{0}_dialect_{1}_dialect_integration.csv".format(region, token))
    dialect_df.to_csv(out_file_path, index=False)

In [13]:
regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]
tokens = ["bpe", "형태소", "jamo", "SentencePiece"]

for r in regions:
    for t in tokens:
        remove_standard("../datas/{0}/".format(r), r, t)
        print("{0} {1} 방언 부분집합만으로 구성 완료".format(r, t))

chungcheong bpe 방언 부분집합만으로 구성 완료
chungcheong 형태소 방언 부분집합만으로 구성 완료
chungcheong jamo 방언 부분집합만으로 구성 완료
chungcheong SentencePiece 방언 부분집합만으로 구성 완료
gangwon bpe 방언 부분집합만으로 구성 완료
gangwon 형태소 방언 부분집합만으로 구성 완료
gangwon jamo 방언 부분집합만으로 구성 완료
gangwon SentencePiece 방언 부분집합만으로 구성 완료
gyeongsang bpe 방언 부분집합만으로 구성 완료
gyeongsang 형태소 방언 부분집합만으로 구성 완료
gyeongsang jamo 방언 부분집합만으로 구성 완료
gyeongsang SentencePiece 방언 부분집합만으로 구성 완료
jeju bpe 방언 부분집합만으로 구성 완료
jeju 형태소 방언 부분집합만으로 구성 완료
jeju jamo 방언 부분집합만으로 구성 완료
jeju SentencePiece 방언 부분집합만으로 구성 완료
jeonla bpe 방언 부분집합만으로 구성 완료
jeonla 형태소 방언 부분집합만으로 구성 완료
jeonla jamo 방언 부분집합만으로 구성 완료
jeonla SentencePiece 방언 부분집합만으로 구성 완료

In [2]:
def calculate_sample_size(path_to_data, region):
    token = "jamo"
    
    file_path = os.path.join(path_to_data, "{0}_dialect_{1}_dialect_integration.csv".format(region, token))
    
    df = pd.read_csv(file_path, index_col=0)
    
    train_size = len(df[df["셋"] == "train"])
    valid_size = len(df[df["셋"] == "val"])
    test_size = len(df[df["셋"] == "test"])
    
    print("{0} 방언 셋 크기: train {2}, val {3}, test {4}".format(region, token, train_size, valid_size, test_size))

In [5]:
def calculate_orginal_sample_size(path_to_data, region):
    token = "jamo"
    
    file_path = os.path.join(path_to_data, "{0}_dialect_{1}_integration.csv".format(region, token))
    
    df = pd.read_csv(file_path, index_col=0)
    
    train_size = len(df[df["셋"] == "train"])
    valid_size = len(df[df["셋"] == "val"])
    test_size = len(df[df["셋"] == "test"])
    
    print("{0} 방언 셋 크기: train {2}, val {3}, test {4}".format(region, token, train_size, valid_size, test_size))

In [3]:
regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    calculate_sample_size("../datas/{0}/".format(r), r)

chungcheong 방언 셋 크기: train 260494, val 15434, test 15621
gangwon 방언 셋 크기: train 557969, val 24203, test 24176
gyeongsang 방언 셋 크기: train 305395, val 14210, test 14181
jeju 방언 셋 크기: train 758384, val 42938, test 42747
jeonla 방언 셋 크기: train 254207, val 25922, test 25777

In [6]:
regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    calculate_orginal_sample_size("../datas/{0}/".format(r), r)

chungcheong 방언 셋 크기: train 520988, val 95000, test 95000
gangwon 방언 셋 크기: train 841540, val 91346, test 91345
gyeongsang 방언 셋 크기: train 610790, val 89512, test 89511
jeju 방언 셋 크기: train 1375435, val 80061, test 80061
jeonla 방언 셋 크기: train 508414, val 110458, test 110459