In [1]:
import os
import json
import pandas as pd
import numpy as np

os.chdir(r"D:\박준호\2024년\NLP-Standard-Dialect-Transformation")
pd.set_option('display.max_colwidth', None)

In [5]:
from metric import compute_chrf_score

강원도 방언 test set 개수 맞추기

In [ ]:
r = "gangwon"
m = "opus-mt"
path_to_trans_result = "./translation_english/prediction/"
path_to_reference = "./translation_english/reference/"

trans_file_path = os.path.join(path_to_trans_result, "{0}/{1}.json".format(r, m))
with open(trans_file_path, mode="rt", encoding="utf-8") as f:
    json_list = json.loads(f.read())
result_df = pd.DataFrame(json_list)

ref_file_path = os.path.join(path_to_reference, "{0}/reference.json".format(r))
with open(ref_file_path, mode="rt", encoding="utf-8") as f:
    json_list = json.loads(f.read())
ref_df = pd.DataFrame(json_list)

# 왜 두 개 길이가 다른가?
opus_source_list = result_df["prediction_source"].to_list()
opus_source_dict = dict(zip(opus_source_list, range(len(opus_source_list))))

excluded_list = []
for i in range(len(ref_df)):
    row = ref_df.iloc[i]
    if row["standard_source"] not in opus_source_dict:
        excluded_list.append(i)

In [23]:
ref_df.iloc[excluded_list]

,standard_source,standard_target
91328,어~ 음식 중에 이제 음식 중에 하나인 것 같아 그리고,I think it's one of the foods now.
91329,음~ 어~ 이제 뼛국 같은 경우도 지금은 해 주 어~ 없어서 못 먹지.,"I think it would be better to translate the sentence as a whole rather than breaking it down. Here is the translation:\n\n""Ah, um, I guess I won't be able to eat it now, huh?"""
91330,어~ 없어서 못 먹지 그게 굉장한 오랜 시간의 정성이 필요한 음식이잖아.,"That's a tough one to give up, you know it takes a lot of effort and time to make that food."
91331,엄청 큰 솥단지에다가 이제 뼈랑 이게 국,A gigantic pot with bones and this is a soup.
91332,그걸 으 야채라든가 이런 걸 넣고 푹 이제,That stuff in it or add some vegetables and now it's okay.
91333,끓이면서 위에 있는 불순물 떠 내고,Boiling and then removing the impurities that float on top.
91334,굉장히 약불로 하다가 굉장한 오랜 시간 동안,Very faintly for a very long time.
91335,그래서 보면은 항상 어머니가 음~ 그걸 만들 때는 큰 솥단지에다가 항상 끓이셨는데,"So then I see, it's always my mom who does it. When she makes that, she always boils it in a big pot."
91336,그러면은 그걸 가지고 진짜 한 한 달은 먹었었던 것 같아 진짜,I think I really ate that for a whole month.
91337,내가 그래서 싫어했었던 것도 같아 왜냐면 한 번에 할 때 많은 양을 하다 보니까,"I used to dislike that too because when I do it all at once, I end up doing a lot."
91338,어렸을 때야 워낙 초딩 입맛이었고 하다 보니,"When I was young, I had a childish taste, and it's been like that ever since."
91339,소고기는 진짜 정확하게 언제 먹었는지 기억은 안 나는 것 같은데 아마,"I think I had beef sometime, but I'm not really sure when."
91340,인제 고기 부패를 많이 갔는데 거기에도 아마 소고기가 있기는 했어.,"I went to Inje and the meat was spoiled a lot, but I think there might have been beef there as well."
91341,근데 질이 굉장히 낮은 고기여 갖고,But the quality is extremely low.
91342,어렸을 때 삼겹살이라던가 거기 항상 냉동이긴 했는데 어~ 그거를 많이 먹었었던 것 같아.,"When I was young, I used to eat a lot of pork belly and it was always frozen there."
91343,먹었었던 것 같아 사실 어~ 젊었을 때나 어렸을 때라던가 이럴 때는 워낙 소고기가 비싸다 보니까,"I was probably able to eat it, but actually, back when I was young or when I was even younger, it was so expensive because of the high price of beef."
91344,내가 일을 하면서 뭔가 쉽사리 접근할 수 있었던 이제 부분은 아니었어서,I couldn't access something easily while working anymore.

이거 그냥 길이로 잘라 버렸네..

대체 왜 그런 짓을?

## 미중일 dirct 성능

In [11]:
def chrf_of_direct_translation(path_to_trans_result, path_to_reference, regions, models, word_order=2):
    
    eval_dict = dict()
    for r in regions:
        print(r)
        result_dict = dict()
        df_len = 0
        for m in models:
            json_list = []
            trans_file_path = os.path.join(path_to_trans_result, "{0}/{1}.json".format(r, m))
            with open(trans_file_path, mode="rt", encoding="utf-8") as f:
                json_list = json.loads(f.read())
            
            df = pd.DataFrame(json_list)
            result_dict[m] = df
            if df_len > 0:
                df_len = min(df_len, len(df))
            else:
                df_len = len(df)
        
        # Load reference data
        ref_file_path = os.path.join(path_to_reference, "{0}/reference.json".format(r))
        with open(ref_file_path, mode="rt", encoding="utf-8") as f:
            json_list = json.loads(f.read())
        
        ref_df = pd.DataFrame(json_list)
        
        r_eval_dict = dict()
        
        # Ensure the reference DataFrame has the same length as the result DataFrames
        
        
        for m in models:
            len_result = len(result_dict[m])
            r_eval_dict[m] = compute_chrf_score(
                y_true=ref_df.iloc[range(len_result)]["standard_target"].to_list(), 
                y_pred=result_dict[m]["dialect_target"].to_list(),
                word_order=word_order
            )

        eval_dict[r] = r_eval_dict
    
    return eval_dict

In [ ]:
regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]
models = ["opus-mt", "m2m_100_1.2B", "exaone"]

eval_dict_chrf = chrf_of_direct_translation("./translation_en/baseline/", "./translation_en/reference/", regions, models)

chungcheong
gangwon
gyeongsang
jeju
jeonla

In [8]:
print(eval_dict_chrf)

{'chungcheong': {'opus-mt': 29.899736299710117, 'm2m_100_1.2B': 29.927620701656622, 'exaone': 41.84524814235252}, 'gangwon': {'opus-mt': 28.11569028009181, 'm2m_100_1.2B': 27.828509422928153, 'exaone': 39.58344502296015}, 'gyeongsang': {'opus-mt': 29.890192821744694, 'm2m_100_1.2B': 29.688938767097884, 'exaone': 42.18258264894414}, 'jeju': {'opus-mt': 25.458562069697656, 'm2m_100_1.2B': 25.157719904722757, 'exaone': 36.639162061946465}, 'jeonla': {'opus-mt': 28.790851705080385, 'm2m_100_1.2B': 28.846113804400535, 'exaone': 40.73570025731394}}

In [33]:
regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]
models = ["m2m_100_1.2B", "exaone"]

eval_dict_chrf = chrf_of_direct_translation("./translation_zh/baseline/", "./translation_zh/reference/", regions, models, word_order=0)

chungcheong
gangwon
gyeongsang
jeju
jeonla

In [34]:
print(eval_dict_chrf)

{'chungcheong': {'m2m_100_1.2B': 10.233893096873826, 'exaone': 13.870981488308445}, 'gangwon': {'m2m_100_1.2B': 9.506399012629473, 'exaone': 13.196685395020877}, 'gyeongsang': {'m2m_100_1.2B': 10.572085041798958, 'exaone': 14.480980567018761}, 'jeju': {'m2m_100_1.2B': 8.736314809763911, 'exaone': 12.103708324401264}, 'jeonla': {'m2m_100_1.2B': 9.958133562191037, 'exaone': 13.488134644613927}}

In [15]:
regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]
models = ["m2m_100_1.2B", "exaone"]

eval_dict_chrf = chrf_of_direct_translation("./translation_jp/baseline/", "./translation_jp/reference/", regions, models, word_order=0)

chungcheong
gangwon
gyeongsang
jeju
jeonla

In [16]:
print(eval_dict_chrf)

{'chungcheong': {'m2m_100_1.2B': 14.257823234391228, 'exaone': 20.964232363478796}, 'gangwon': {'m2m_100_1.2B': 12.520343934959389, 'exaone': 19.435285698119962}, 'gyeongsang': {'m2m_100_1.2B': 14.329880040577816, 'exaone': 21.508564801948456}, 'jeju': {'m2m_100_1.2B': 10.760888324268258, 'exaone': 17.06342426369407}, 'jeonla': {'m2m_100_1.2B': 13.8149272022079, 'exaone': 20.435548142894913}}

In [27]:
region = "chungcheong"
model = "exaone"
path_to_translation = "./translation_english/"

file_path = os.path.join(path_to_translation, "reference/{0}/reference.json".format(region))
    
json_list = []

with open(file_path, mode="rt", encoding="utf-8") as f:
    json_list = json.loads(f.read())

reference_df = pd.DataFrame(json_list)

file_path = os.path.join(path_to_translation, "prediction/{0}/{1}.json".format(region, model))
        
with open(file_path, mode="rt", encoding="utf-8") as f:
    json_list = json.loads(f.read())

pred_df = pd.DataFrame(json_list)

In [28]:
print(len(pred_df), len(reference_df))

95000 95000

In [18]:
def chrf_of_prediction(path_to_translation, region, model, word_order=2):
    file_path = os.path.join(path_to_translation, "reference/{0}/reference.json".format(region))
    
    json_list = []

    with open(file_path, mode="rt", encoding="utf-8") as f:
        json_list = json.loads(f.read())

    reference_df = pd.DataFrame(json_list)
    
    file_path = os.path.join(path_to_translation, "prediction/{0}/{1}.json".format(region, model))
        
    with open(file_path, mode="rt", encoding="utf-8") as f:
        json_list = json.loads(f.read())
        
    pred_df = pd.DataFrame(json_list)
    
    # 방언 부분집합 걸러내기
    
    # 두가지 점수 구하기
    score_dict = dict()
    
    len_result = len(pred_df)
    pred_score = compute_chrf_score(
        y_pred=pred_df["prediction_target"].to_list(),
        y_true=reference_df.iloc[range(len_result)]["standard_target"].to_list(),
        word_order=word_order
    )
    
    score_dict={"pred_chrf": pred_score}
    
    return score_dict

## 영어 pivot 성능

In [19]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = chrf_of_prediction("./translation_en/", r, "opus-mt")
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'pred_chrf': 30.041264515912943}, 'gangwon': {'pred_chrf': 28.35038718480748}, 'gyeongsang': {'pred_chrf': 30.06574848038776}, 'jeju': {'pred_chrf': 26.916914658319385}, 'jeonla': {'pred_chrf': 28.869409988253203}}

In [20]:
for r in regions:
    print(r)
    score_dict = chrf_of_prediction("./translation_en/", r, "m2m_100_1.2B")
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'pred_chrf': 30.14948841492747}, 'gangwon': {'pred_chrf': 28.12401964733348}, 'gyeongsang': {'pred_chrf': 29.841671013957555}, 'jeju': {'pred_chrf': 26.690496367237614}, 'jeonla': {'pred_chrf': 29.0406218919269}}

In [21]:
for r in regions:
    print(r)
    score_dict = chrf_of_prediction("./translation_en/", r, "exaone")
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'pred_chrf': 41.9058010544727}, 'gangwon': {'pred_chrf': 39.61855267669251}, 'gyeongsang': {'pred_chrf': 42.09081791831114}, 'jeju': {'pred_chrf': 38.13848886796272}, 'jeonla': {'pred_chrf': 40.593375002203274}}

## 일본어 pivot 성능

In [31]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = chrf_of_prediction("./translation_jp/", r, "m2m_100_1.2B", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'pred_chrf': 14.380678718196432}, 'gangwon': {'pred_chrf': 12.68876939091021}, 'gyeongsang': {'pred_chrf': 14.424158191952651}, 'jeju': {'pred_chrf': 11.599434528493884}, 'jeonla': {'pred_chrf': 13.857333367274165}}

In [32]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = chrf_of_prediction("./translation_jp/", r, "exaone", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'pred_chrf': 21.050896101710048}, 'gangwon': {'pred_chrf': 19.503125276915007}, 'gyeongsang': {'pred_chrf': 21.60154817262145}, 'jeju': {'pred_chrf': 17.85871736903309}, 'jeonla': {'pred_chrf': 20.39325998434969}}

## 중국어 pivot 성능

In [35]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = chrf_of_prediction("./translation_zh/", r, "m2m_100_1.2B", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'pred_chrf': 10.334205253657267}, 'gangwon': {'pred_chrf': 9.648737011157108}, 'gyeongsang': {'pred_chrf': 10.62066027505951}, 'jeju': {'pred_chrf': 9.44489134653512}, 'jeonla': {'pred_chrf': 10.008641792506038}}

In [36]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = chrf_of_prediction("./translation_zh/", r, "exaone", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'pred_chrf': 13.896448603001646}, 'gangwon': {'pred_chrf': 13.221778251097671}, 'gyeongsang': {'pred_chrf': 14.433445920854501}, 'jeju': {'pred_chrf': 12.735064472551002}, 'jeonla': {'pred_chrf': 13.423115083350293}}

# 방언 부분집합에서의 chrf 성능

In [13]:
def evaluate_subset_chrf(path_to_translation, region, model, word_order=2):
    file_path = os.path.join(path_to_translation, "reference/{0}/reference.json".format(region))
    
    json_list = []

    with open(file_path, mode="rt", encoding="utf-8") as f:
        json_list = json.loads(f.read())

    reference_df = pd.DataFrame(json_list)
    
    file_path = os.path.join(path_to_translation, "prediction/{0}/{1}.json".format(region, model))
        
    with open(file_path, mode="rt", encoding="utf-8") as f:
        json_list = json.loads(f.read())
        
    pred_df = pd.DataFrame(json_list)
    
    trans_file_path = os.path.join(path_to_translation, "baseline/{0}/{1}.json".format(region, model))
    with open(trans_file_path, mode="rt", encoding="utf-8") as f:
        json_list = json.loads(f.read())
            
    base_df = pd.DataFrame(json_list)
    
    # reference는 잘라서 base_df와 같은 길이로 맞춘 후 비교
    ref_cut_df = reference_df.iloc[range(len(base_df))]
    # standard와 dialect가 다른 index 구하기
    dialect_index = base_df[base_df["dialect_source"] != base_df["standard_source"]].index
    
    ref_dia_df = reference_df.loc[dialect_index]
    pred_dia_df = pred_df.loc[dialect_index]
    base_dia_df = base_df.loc[dialect_index]
    
    # 두가지 점수 구하기
    score_dict = dict()
    
    pred_score = compute_chrf_score(
        pred_dia_df["prediction_target"].to_list(),
        ref_dia_df["standard_target"].to_list(),
        word_order=word_order
    )
    
    base_score = compute_chrf_score(
        base_dia_df["dialect_target"].to_list(),
        ref_dia_df["standard_target"].to_list(),
        word_order=word_order
    )
    
    score_dict={"baseline_chrf_score": base_score, "pred_chrf_score": pred_score}
    
    return score_dict

## 영어

In [14]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_en/", r, "exaone")
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 39.75246369598926, 'pred_chrf_score': 40.26371057999242}, 'gangwon': {'baseline_chrf_score': 37.17624374881765, 'pred_chrf_score': 38.005152753710576}, 'gyeongsang': {'baseline_chrf_score': 39.80419059159144, 'pred_chrf_score': 40.20415838310234}, 'jeju': {'baseline_chrf_score': 33.85651325730458, 'pred_chrf_score': 36.72202912821502}, 'jeonla': {'baseline_chrf_score': 39.81309536553755, 'pred_chrf_score': 40.07841763036248}}

In [9]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_en/", r, "m2m_100_1.2B")
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 28.124741018254134, 'pred_chrf_score': 29.478717444356423}, 'gangwon': {'baseline_chrf_score': 25.60500946392802, 'pred_chrf_score': 27.16341916130713}, 'gyeongsang': {'baseline_chrf_score': 27.638315018388, 'pred_chrf_score': 28.952599172233022}, 'jeju': {'baseline_chrf_score': 22.967296949015193, 'pred_chrf_score': 25.85655312407343}, 'jeonla': {'baseline_chrf_score': 27.6630154203347, 'pred_chrf_score': 28.879253570990947}}

In [10]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_en/", r, "opus-mt")
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 28.05601984547281, 'pred_chrf_score': 29.046943849400193}, 'gangwon': {'baseline_chrf_score': 25.952427836136376, 'pred_chrf_score': 27.446956565562168}, 'gyeongsang': {'baseline_chrf_score': 27.817317495896976, 'pred_chrf_score': 29.001072448781713}, 'jeju': {'baseline_chrf_score': 23.296389220058085, 'pred_chrf_score': 26.04052747729348}, 'jeonla': {'baseline_chrf_score': 27.857893335410605, 'pred_chrf_score': 28.650236356880054}}

## 중국어

In [16]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_zh/", r, "exaone", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 12.32699326566935, 'pred_chrf_score': 12.554416791166146}, 'gangwon': {'baseline_chrf_score': 12.009028658482505, 'pred_chrf_score': 12.386092366871674}, 'gyeongsang': {'baseline_chrf_score': 13.15682607813303, 'pred_chrf_score': 13.262393454122954}, 'jeju': {'baseline_chrf_score': 10.822061879699445, 'pred_chrf_score': 12.017664536767224}, 'jeonla': {'baseline_chrf_score': 12.714763658988485, 'pred_chrf_score': 12.801281143479057}}

In [11]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_zh/", r, "m2m_100_1.2B", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 8.735376913136896, 'pred_chrf_score': 9.282320986207884}, 'gangwon': {'baseline_chrf_score': 8.18207343700827, 'pred_chrf_score': 8.918892413762093}, 'gyeongsang': {'baseline_chrf_score': 9.032407348642817, 'pred_chrf_score': 9.554123238629222}, 'jeju': {'baseline_chrf_score': 7.618584155801206, 'pred_chrf_score': 8.932896935822594}, 'jeonla': {'baseline_chrf_score': 9.005054015619756, 'pred_chrf_score': 9.49490429734939}}

## 일본어

In [15]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_jp/", r, "exaone", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 19.083349358899483, 'pred_chrf_score': 19.765332951381247}, 'gangwon': {'baseline_chrf_score': 17.917181406060482, 'pred_chrf_score': 18.46730339699933}, 'gyeongsang': {'baseline_chrf_score': 19.685937878126182, 'pred_chrf_score': 20.670973653550035}, 'jeju': {'baseline_chrf_score': 15.424446021727508, 'pred_chrf_score': 16.965267471341235}, 'jeonla': {'baseline_chrf_score': 19.43596782322621, 'pred_chrf_score': 19.687805803132058}}

In [12]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_jp/", r, "m2m_100_1.2B", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 12.705530022196406, 'pred_chrf_score': 13.416859080299167}, 'gangwon': {'baseline_chrf_score': 10.990917665432958, 'pred_chrf_score': 11.899006437801681}, 'gyeongsang': {'baseline_chrf_score': 12.943754649730332, 'pred_chrf_score': 13.732618752066406}, 'jeju': {'baseline_chrf_score': 9.381469627821007, 'pred_chrf_score': 10.94405404500067}, 'jeonla': {'baseline_chrf_score': 13.026874716979972, 'pred_chrf_score': 13.588006138311679}}

# 방언 부분 집합에서의 chrf 성능2

다만 여기서는 방언 부분집합만 가지고 다시 실험한 결과를 기록

## 영어

In [7]:
def evaluate_subset_chrf(path_to_translation, region, model, word_order=2):
    file_path = os.path.join(path_to_translation, "reference/{0}/reference.json".format(region))
    
    json_list = []

    with open(file_path, mode="rt", encoding="utf-8") as f:
        json_list = json.loads(f.read())

    reference_df = pd.DataFrame(json_list)
    
    file_path = os.path.join(path_to_translation, "prediction_sub/{0}/{1}.json".format(region, model))
        
    with open(file_path, mode="rt", encoding="utf-8") as f:
        json_list = json.loads(f.read())
        
    pred_df = pd.DataFrame(json_list)
    
    trans_file_path = os.path.join(path_to_translation, "baseline/{0}/{1}.json".format(region, model))
    with open(trans_file_path, mode="rt", encoding="utf-8") as f:
        json_list = json.loads(f.read())
            
    base_df = pd.DataFrame(json_list)
    
    # standard와 dialect가 다른 index 구하기
    dialect_index = base_df[base_df["dialect_source"] != base_df["standard_source"]].index
    
    ref_dia_df = reference_df.loc[dialect_index]
    #pred_dia_df = pred_df.loc[dialect_index]
    # pred_df는 이미 dialect만 포함되어 있는 상태
    pred_dia_df = pred_df
    base_dia_df = base_df.loc[dialect_index]
    
    
    # 길이가 다르면 짧은 쪽에 맞춘다.
    # 이전에 reference 만들 때에도 baseline에 맞추어 tail을 잘라내는 가공을 하였으니
    # prediction에서도 동일하게 tail을 잘라내면 문제가 없을 것이다.
    if len(ref_dia_df) < len(pred_dia_df):
        ref_len = len(ref_dia_df)
        pred_dia_df = pred_dia_df.iloc[:ref_len]
    
    
    # 두가지 점수 구하기
    score_dict = dict()
    
    pred_score = compute_chrf_score(
        pred_dia_df["prediction_target"].to_list(),
        ref_dia_df["standard_target"].to_list(),
        word_order=word_order
    )
    
    base_score = compute_chrf_score(
        base_dia_df["dialect_target"].to_list(),
        ref_dia_df["standard_target"].to_list(),
        word_order=word_order
    )
    
    score_dict={"baseline_chrf_score": base_score, "pred_chrf_score": pred_score}
    
    return score_dict

In [8]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_en/", r, "exaone")
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 39.75246369598926, 'pred_chrf_score': 40.2178694300006}, 'gangwon': {'baseline_chrf_score': 37.17624374881765, 'pred_chrf_score': 38.35850792965107}, 'gyeongsang': {'baseline_chrf_score': 39.80419059159144, 'pred_chrf_score': 40.45190247981093}, 'jeju': {'baseline_chrf_score': 33.85651325730458, 'pred_chrf_score': 36.7535068818742}, 'jeonla': {'baseline_chrf_score': 39.81309536553755, 'pred_chrf_score': 40.37303020211554}}

In [9]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_en/", r, "m2m_100_1.2B")
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 28.124741018254134, 'pred_chrf_score': 29.544916212000423}, 'gangwon': {'baseline_chrf_score': 25.60500946392802, 'pred_chrf_score': 27.434547129335673}, 'gyeongsang': {'baseline_chrf_score': 27.638315018388, 'pred_chrf_score': 29.172876462662916}, 'jeju': {'baseline_chrf_score': 22.967296949015193, 'pred_chrf_score': 25.941046173833293}, 'jeonla': {'baseline_chrf_score': 27.6630154203347, 'pred_chrf_score': 29.26676875131139}}

In [10]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_en/", r, "opus-mt")
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 28.05601984547281, 'pred_chrf_score': 29.103593664831962}, 'gangwon': {'baseline_chrf_score': 25.952427836136376, 'pred_chrf_score': 27.830111637293054}, 'gyeongsang': {'baseline_chrf_score': 27.817317495896976, 'pred_chrf_score': 29.1883419010097}, 'jeju': {'baseline_chrf_score': 23.296389220058085, 'pred_chrf_score': 26.06004281471935}, 'jeonla': {'baseline_chrf_score': 27.857893335410605, 'pred_chrf_score': 28.96262491591861}}

## 중국어

In [13]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_zh/", r, "exaone", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 12.32699326566935, 'pred_chrf_score': 12.596927180721067}, 'gangwon': {'baseline_chrf_score': 12.009028658482505, 'pred_chrf_score': 12.501485250753886}, 'gyeongsang': {'baseline_chrf_score': 13.15682607813303, 'pred_chrf_score': 13.307681466952312}, 'jeju': {'baseline_chrf_score': 10.822061879699445, 'pred_chrf_score': 12.085014498018651}, 'jeonla': {'baseline_chrf_score': 12.714763658988485, 'pred_chrf_score': 12.937327051527905}}

In [14]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_zh/", r, "m2m_100_1.2B", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 8.735376913136896, 'pred_chrf_score': 9.372693233777348}, 'gangwon': {'baseline_chrf_score': 8.18207343700827, 'pred_chrf_score': 9.123055587112866}, 'gyeongsang': {'baseline_chrf_score': 9.032407348642817, 'pred_chrf_score': 9.688577671391577}, 'jeju': {'baseline_chrf_score': 7.618584155801206, 'pred_chrf_score': 9.018477500945133}, 'jeonla': {'baseline_chrf_score': 9.005054015619756, 'pred_chrf_score': 9.669568116780427}}

## 일본어

In [15]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_jp/", r, "exaone", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 19.083349358899483, 'pred_chrf_score': 19.697109468212616}, 'gangwon': {'baseline_chrf_score': 17.917181406060482, 'pred_chrf_score': 18.601197807257293}, 'gyeongsang': {'baseline_chrf_score': 19.685937878126182, 'pred_chrf_score': 20.671303831431345}, 'jeju': {'baseline_chrf_score': 15.424446021727508, 'pred_chrf_score': 17.053438617986526}, 'jeonla': {'baseline_chrf_score': 19.43596782322621, 'pred_chrf_score': 19.91514473472424}}

In [16]:
eval_dict = dict()

regions = ["chungcheong", "gangwon", "gyeongsang", "jeju", "jeonla"]

for r in regions:
    print(r)
    score_dict = evaluate_subset_chrf("./translation_jp/", r, "m2m_100_1.2B", word_order=0)
    eval_dict[r] = score_dict
    
print(eval_dict)

chungcheong
gangwon
gyeongsang
jeju
jeonla
{'chungcheong': {'baseline_chrf_score': 12.705530022196406, 'pred_chrf_score': 13.50859709216103}, 'gangwon': {'baseline_chrf_score': 10.990917665432958, 'pred_chrf_score': 12.094897935584541}, 'gyeongsang': {'baseline_chrf_score': 12.943754649730332, 'pred_chrf_score': 13.833520659698898}, 'jeju': {'baseline_chrf_score': 9.381469627821007, 'pred_chrf_score': 11.019927785138991}, 'jeonla': {'baseline_chrf_score': 13.026874716979972, 'pred_chrf_score': 13.779988348695937}}

# 방언 부분집합의 비율

In [38]:
r = "gyeongsang"
m = "opus-mt"
path_to_trans_result = "./translation_en/baseline/"
path_to_reference = "./translation_en/reference/"

trans_file_path = os.path.join(path_to_trans_result, "{0}/{1}.json".format(r, m))
with open(trans_file_path, mode="rt", encoding="utf-8") as f:
    json_list = json.loads(f.read())

result_df = pd.DataFrame(json_list)
dialect_df = result_df[result_df["dialect_source"] != result_df["standard_source"]]

In [39]:
print(len(result_df), len(dialect_df))

89472 14174

In [40]:
r = "jeonla"

trans_file_path = os.path.join(path_to_trans_result, "{0}/{1}.json".format(r, m))
with open(trans_file_path, mode="rt", encoding="utf-8") as f:
    json_list = json.loads(f.read())

result_df = pd.DataFrame(json_list)
dialect_df = result_df[result_df["dialect_source"] != result_df["standard_source"]]

In [41]:
print(len(result_df), len(dialect_df))

110080 25727

In [42]:
r = "jeju"

trans_file_path = os.path.join(path_to_trans_result, "{0}/{1}.json".format(r, m))
with open(trans_file_path, mode="rt", encoding="utf-8") as f:
    json_list = json.loads(f.read())

result_df = pd.DataFrame(json_list)
dialect_df = result_df[result_df["dialect_source"] != result_df["standard_source"]]

In [ ]:
print(len(result_df), len(dialect_df))

79872 42669

In [44]:
r = "gangwon"

trans_file_path = os.path.join(path_to_trans_result, "{0}/{1}.json".format(r, m))
with open(trans_file_path, mode="rt", encoding="utf-8") as f:
    json_list = json.loads(f.read())

result_df = pd.DataFrame(json_list)
dialect_df = result_df[result_df["dialect_source"] != result_df["standard_source"]]

In [45]:
print(len(result_df), len(dialect_df))

91008 24084

In [46]:
r = "chungcheong"

trans_file_path = os.path.join(path_to_trans_result, "{0}/{1}.json".format(r, m))
with open(trans_file_path, mode="rt", encoding="utf-8") as f:
    json_list = json.loads(f.read())

result_df = pd.DataFrame(json_list)
dialect_df = result_df[result_df["dialect_source"] != result_df["standard_source"]]

In [47]:
print(len(result_df), len(dialect_df))

94848 15601

# column 문제 확인

일본어 경상 방언 baseline에서 방언과 표준어가 반대로 레이블되어 있는 경우를 발견

In [19]:
r = "gyeongsang"
m = "exaone"
path_to_trans_result = "./translation_jp/baseline/"

trans_file_path = os.path.join(path_to_trans_result, "{0}/{1}.json".format(r, m))
with open(trans_file_path, mode="rt", encoding="utf-8") as f:
    json_list = json.loads(f.read())

result_df = pd.DataFrame(json_list)
dialect_df = result_df[result_df["dialect_source"] != result_df["standard_source"]]

dialect_df.head(10)

,standard_source,standard_target,dialect_source,dialect_target
3,성격이 일단 제가 조금 막 드센 건 아닌데,性格は私が少し厳しい方ですが。,성격이 일단 제가 쫌 막 드센 건 아닌데,性格は私がちょっと厳しいかもしれませんが。
12,이게 그냥 이렇게 딱 사는 것보다 내가 직접,これはただこういったように生きるよりも私が直接。,이게 그냥 이케 딱 사는 것보다 내가 직접,これはただこう生きるよりも私が直接。
30,그러면 이제 학생이라고 하셨는데 name 님은 만약에 나중에,それでは、今や学生だとおっしゃいましたが、名前さんはもし後に。,그면 이제 학생이라고 하셨는데 name 님은 만약에 나중에,それでは、今や学生だとおっしゃいましたが、名前さんはもし後に。
38,그러면 name 님은 데이트 비용은 어떻게 하세요?,それでは、nameさんはデートの費用はどうしますか?,그면 name 님은 데이트 비용은 어떻게 하세요?,それならば、nameさんはデートの費用はどうしますか?
40,이거는 조금 아닌 것 같고 만약에 그쪽이 조금 덜 여유롭고,これは少し違うようで、もしあなたが少し余裕がない場合。,이거는 쫌 아닌 것 같고 만약에 그쪽이 쫌 덜 여유롭고,これはちょっと違う気がしていて、もしあなたがちょっと余裕がない場合。
51,고런 거 조금 배려를 해줬으면 좋겠습니다.,そんなこと少し考えてくれればいいです。,고런 거 쫌 배려를 해줬으면 좋겠습니다.,そんなことちょっと配慮してくれればいいです。
66,앞으로의 계획 같은 게 아무래도 조금 있어야 하는 데,これからの計画とか、どうやら少し必要かもしれない。,앞으로의 계획 같은 게 아무래도 쫌 있어야 하는 데,これからの計画とか、どうやら少し必要かもしれないんだけど。
83,아들 낳으면 너는 평생 후회한다.,男の子を産むと、あなたは一生懸命後悔するでしょう。,아들 놓으면 너는 평생 후회한다.,子供を産むと、あなたは終生後悔するでしょう。
85,저는 아들 하나 딸 하나 낳고 싶지만,私は息子一人娘一人を望んでいますが。,저는 아들 하나 딸 하나 놓고 싶지만,私は息子一人娘一人を欲しています。
89,이제 여자 친구 입장에서는 왜 의견 없이 왜 네 주장 없이,今や女性の友達の立場からすると、なぜ意見なしで、なぜ主張なしで。,이제 여자 친구 입장에서는 왜 의견 없이 왜 니 주장 없이,今や女性の友達の立場からすると、なぜ意見なしで、なぜ主張なしで。

scorpio 서버 내 exaone 모델 baseline에서 경상, 제주, 충청, 강원 방언의 column이 방언과 표준어가 뒤바뀐 것을 발견.

다른 서버에서도 해당 현상 확인 필요

# 방언 부분집합에서 방언 정규화 성능 측정

In [ ]:
def prediction_chrf_dialect(region, token):
    file_path = "D:/박준호/2024년/standard-dialect/model_storage/dia_to_sta/{0}/{1}/prediction.json".format(region, token)
    
    prediction_list = []
    with open(file_path, mode="r+", encoding="utf-16") as fp:
        prediction_list = json.loads(fp.read())
    
    df = pd.DataFrame(prediction_list)
    df = df.loc[df["truth"] != df["source"]]
    
    score = compute_chrf_score(df["pred"].to_list(), df["source"].to_list())
    
    return score

In [21]:
regions = ["gyeongsang", "jeonla", "jeju", "gangwon", "chungcheong"]
tokens = ["SentencePiece", "bpe", "형태소", "jamo"]

for r in regions:
    print(r)
    for t in tokens:
        print(t)
        score = prediction_chrf_dialect(r, t)
        print(score)

gyeongsang
SentencePiece
47.87847874460936
bpe
40.04685019895429
형태소
51.566971691406216
jamo
86.2589146397298
jeonla
SentencePiece
55.142739798834896
bpe
61.1409195440998
형태소
76.62617155543963
jamo
85.6316550116013
jeju
SentencePiece
39.771399534183274
bpe
33.773069938668534
형태소
63.67341626085092
jamo
72.26599140861629
gangwon
SentencePiece
50.486567221488464
bpe
42.79422131372604
형태소
75.77401436373209
jamo
85.37316054467146
chungcheong
SentencePiece
49.93390786133574
bpe
22.6419481990477
형태소
80.1336316569632
jamo
88.20171835238698

In [22]:
from metric import compute_bleu_score

def prediction_bleu_dialect(region, token):
    file_path = "D:/박준호/2024년/standard-dialect/model_storage/dia_to_sta/{0}/{1}/prediction.json".format(region, token)
    
    prediction_list = []
    with open(file_path, mode="r+", encoding="utf-16") as fp:
        prediction_list = json.loads(fp.read())
    
    df = pd.DataFrame(prediction_list)
    df = df.loc[df["truth"] != df["source"]]
    
    bleu = compute_bleu_score(df["pred"].to_list(), df["source"].to_list())
    
    return bleu

In [23]:
regions = ["gyeongsang", "jeonla", "jeju", "gangwon", "chungcheong"]
tokens = ["SentencePiece", "bpe", "형태소", "jamo"]

for r in regions:
    print(r)
    for t in tokens:
        print(t)
        score = prediction_bleu_dialect(r, t)
        print(score)

gyeongsang
SentencePiece
0.5937175769983204
bpe
0.5299074122060874
형태소
0.6286665849576094
jamo
0.9079915306827956
jeonla
SentencePiece
0.6541680865883255
bpe
0.7157315568059021
형태소
0.8516163496463104
jamo
0.9083159521425683
jeju
SentencePiece
0.5335371588104575
bpe
0.4481131123680699
형태소
0.7393943453988485
jamo
0.8036854577606481
gangwon
SentencePiece
0.6330460933493508
bpe
0.5507751105749443
형태소
0.8497306303877893
jamo
0.906145056004294
chungcheong
SentencePiece
0.6063829432783769
bpe
0.3426229005613501
형태소
0.8731230436057837
jamo
0.9229820342904244

# mingru와 gru 비교

In [26]:
def prediction_chrf_dialect_path(prediction_path, region, token):
    file_path = os.path.join(prediction_path, "{0}/{1}/prediction.json".format(region, token))
    
    prediction_list = []
    with open(file_path, mode="r+", encoding="utf-16") as fp:
        prediction_list = json.loads(fp.read())
    
    df = pd.DataFrame(prediction_list)
    df = df.loc[df["truth"] != df["source"]]
    
    score = compute_chrf_score(df["pred"].to_list(), df["source"].to_list())
    
    return score

In [28]:
def prediction_bleu_dialect_path(prediction_path, region, token):
    file_path = os.path.join(prediction_path, "{0}/{1}/prediction.json".format(region, token))
    
    prediction_list = []
    with open(file_path, mode="r+", encoding="utf-16") as fp:
        prediction_list = json.loads(fp.read())
    
    df = pd.DataFrame(prediction_list)
    df = df.loc[df["truth"] != df["source"]]
    
    score = compute_bleu_score(df["pred"].to_list(), df["source"].to_list())
    
    return score

In [27]:
regions = ["gyeongsang", "jeonla", "jeju", "gangwon", "chungcheong"]
tokens = ["jamo"]
file_path = "./model_storage/dia_to_sta_gru/"

for r in regions:
    print(r)
    for t in tokens:
        print(t)
        score = prediction_chrf_dialect_path(file_path, r, t)
        print(score)

gyeongsang
jamo
85.16006472551766
jeonla
jamo
85.83668867260128
jeju
jamo
72.41408354060182
gangwon
jamo
86.68197749810224
chungcheong
jamo
88.3917130281674

In [29]:
for r in regions:
    print(r)
    for t in tokens:
        print(t)
        score = prediction_bleu_dialect_path(file_path, r, t)
        print(score)

gyeongsang
jamo
0.9003129551642387
jeonla
jamo
0.9090099348284935
jeju
jamo
0.8039275138797782
gangwon
jamo
0.9168430502036784
chungcheong
jamo
0.9160355547323324